# Generated by Django 4.2.30 on 2026-06-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='subscription_notes',
            field=models.TextField(blank=True, help_text='Internal notes about payment/subscription status'),
        ),
    ]
