# Generated by Django 4.2.30 on 2026-06-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_add_palengke_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='menu_image',
            field=models.ImageField(blank=True, help_text='Store menu flyer (optional): Upload your digital menu or price list', upload_to='menus/'),
        ),
    ]
